<a href="https://colab.research.google.com/github/jufabeck2202/KI-Lab/blob/main/aufgabe6/DeepReinforcementlearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

General idea:
1. Use a neural network that takes as input a state (represented as numbers)
and outputs a probability for every action.
2. Generate episodes by inputing the current state into the network and
sampling actions from the network’s output. Remember the
<state, action> pairs for every episode.
3. From these episodes, identify the ones with the highest reward.
4. Use the <state, action> pairs from those high reward episodes as
training examples for improving the neural network.
5. Go back to step 2

Task 2
1. Define a neural network with two fully connected-layers. The hidden layer uses a
Relu activation. The output layer uses a softmax. Try different hidden layer sizes
(between 100 and 500). The network takes as input a vector of the current states
and gives out a probability for each action.
2. Generate 100 episodes by sampling actions using the network output. Limit the
number of steps per episode to 500. Sum up the reward of all steps of one episode.
3. Print out the mean reward per episode of the 100 episodes.
4. Identify the 20 best of those episodes in terms of reward and use the
<state, action> pairs of these episodes as training examples for the network.
5. Update the weights of the network by performing backpropagation on these <state,
action> pairs.
6. Repeat steps 2 to 5 until a mean reward of 100 is reached.
7. Record a video of the lunar lander by running the trained network on one additional
episode.

Hints
* Use !pip3 install box2d-py to make the environment work in Colab.
* You cannot show the video of your lander in Colab (env.render() fails).  
* Workaround: Download the model on your local machine and record the video there,
using recording_demo.py as template (see Mattermost).
* The loss is not a useful indicator for the learning progress in RL. Instead check how
the mean reward develops over time.
* The mean reward will jump back and forth quite a bit, but overall should increase.
* After roughly 70 training iterations the mean reward should be positive, and after
roughly 100 steps be over 100.
* Note that these numbers depend on your parameter setting and it may also take
longer or shorter.
* Reinforcement learning is much more difficult than supervised learning, you have to
play around quite a bit to get things into the right direction.

# Imports

In [1]:
!pip3 install box2d-py gym > /dev/null

In [2]:
import gym
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import heapq
import random
import torch.optim as optim
%matplotlib inline


In [3]:
env = gym.make('LunarLander-v2')
rewards = []

##get Action space
print(env.observation_space.shape)
print(env.action_space)
print()
print(env.observation_space.sample())
print(env.action_space.sample())


(8,)
Discrete(4)

[-1.4245257 -0.5118405 -2.3372087 -0.2351139  0.5469467  1.0710894
  0.6966683 -1.2581046]
2


# Define Network

In [4]:

class Network(nn.Module):

    def __init__(self, hidden_size,):
        super(Network, self).__init__()
        self.fc1 = nn.Linear(env.observation_space.shape[0], hidden_size)
        self.fc2 = nn.Linear(hidden_size, env.action_space.n)
        
    def forward(self, x):
        h = F.relu(self.fc1(x))
        return self.fc2(h)

In [5]:
net = Network(200)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(params=net.parameters(), lr=0.01)


# Sample Episodes

In [6]:
# get episodes
def sample(episodes_n=100, max_steps=5000):
  episodes_data = []
  
  softmax = nn.Softmax(dim=1)
  for i_episode in range(episodes_n):
      steps = [] # steps[0] is the action, steps[1] is the state
      total_reward = 0
      state = env.reset()
      for i_step in range(max_steps):

          state_vector = torch.FloatTensor([state])
          probability= softmax(net(state_vector))

          selected_action = np.random.choice(len(probability.data.numpy()[0]), p=probability.data.numpy()[0])
          new_state, reward, done, info = env.step(selected_action)

          rewards.append(reward)
          #important: use old state
          
          steps.append([selected_action, state])
          state = new_state
          total_reward += reward
          

          if done:
              episodes_data.append({ "total_reward": total_reward  ,"steps": steps})
              break
      #print(f"Mean reward of episode {i_episode}: {np.array(rewards).mean()}")
  return episodes_data


In [7]:
def calculate_total_mean_reward(all_episodes):
   all_rewards = [d['total_reward'] for d in all_episodes]
   return np.array(all_rewards).mean()

In [8]:
def get_top_20(all_episodes):
  return heapq.nlargest(20, all_episodes, key=lambda s: s['total_reward'])

In [9]:
def filter_batch(all_episodes,percentile=80):

    rewards_batch = [d['total_reward'] for d in all_episodes]
    reward_threshold = np.percentile(rewards_batch, percentile)
   
    top_20_p_episodes = []
    for episode in all_episodes:
      if episode['total_reward'] > reward_threshold:
        top_20_p_episodes.append(episode)
    return top_20_p_episodes

In [17]:
def get_training_data_batch(data):
  observations = []
  targets = []
  for entry in data:
    for step in entry['steps']:
      #state
      observations.append(step[1])
      #action
      targets.append(step[0])

  return [observations, targets]

In [20]:
def train_batch():
  
  # get the inputs; data is a list of [inputs, labels]
  training_data = sample(episodes_n=100)
  best_20 = filter_batch(training_data)
  observations, targets = get_training_data_batch(best_20)

  # calculate mean for the current episodes:

  #convert to torch?
  optimizer.zero_grad()
  observations=torch.FloatTensor(observations)
  targets =torch.LongTensor(targets)
  print(targets)

  # forward + backward + optimize
  action_pred = net(observations)

  loss = criterion(action_pred, targets)
  loss.backward()
  optimizer.step()
  reward_complete = calculate_total_mean_reward(training_data)
  print(f"Mean Reward for Sampling 100 episodes {reward_complete}, Loss: {loss}")
  return reward_complete

  



In [ ]:
while True:
  if 150 < train_batch():
    break


Mean Reward for Sampling 100 episodes -196.60228404754926
tensor([1, 2, 0,  ..., 3, 3, 0])
Loss 1.384766936302185
Mean Reward for Sampling 100 episodes -220.61793407841094
tensor([3, 2, 3,  ..., 2, 1, 0])
Loss 1.3678103685379028
Mean Reward for Sampling 100 episodes -166.4845348592457
tensor([0, 2, 3,  ..., 2, 0, 3])
Loss 1.3699756860733032
Mean Reward for Sampling 100 episodes -130.7830805766738
tensor([3, 3, 1,  ..., 0, 2, 2])
Loss 1.3674547672271729
Mean Reward for Sampling 100 episodes -134.91141081156007
tensor([0, 1, 1,  ..., 2, 0, 2])
Loss 1.36702561378479
Mean Reward for Sampling 100 episodes -128.79395277045592
tensor([3, 0, 1,  ..., 2, 2, 3])
Loss 1.355222463607788
Mean Reward for Sampling 100 episodes -129.63727039946968
tensor([0, 3, 2,  ..., 0, 1, 1])
Loss 1.3329724073410034
Mean Reward for Sampling 100 episodes -108.0421215520677
tensor([1, 3, 3,  ..., 1, 0, 1])
Loss 1.3051036596298218
Mean Reward for Sampling 100 episodes -129.3496454057254
tensor([2, 2, 3,  ..., 2, 2, 0

# Deprecated code

In [ ]:
# depricated code
def get_training_data(episode_data):
  train_data = []
  for entry in episodes_data:
    for step in entry['steps']:
      one_hot = np.zeros(env.action_space.n)
      one_hot[step[0]] = 1
      train_data.append([one_hot, step[1]])
  return train_data

def train(training_data):
  for data in training_data:
    optimizer.zero_grad()
    # get the inputs; data is a list of [inputs, labels]
    action, observation = data
    #convert to torch?
    observation=torch.from_numpy(np.expand_dims(observation, axis=0))
    action =torch.from_numpy(np.array([np.argmax(action, axis=0)]))


    # forward + backward + optimize
    output_action = net(observation)
    loss = criterion(output_action, action)
    loss.backward()
    optimizer.step()

while False:
  episodes_data = sample(episodes_n=200)
  print(f"Mean Reward for Sampling 20 episodes {calculate_total_mean_reward(episodes_data)}")
  best_20 = get_top_20(episodes_data)
  train(get_training_data(best_20))

# Download Video

Code found [here](https://colab.research.google.com/github/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_12_01_ai_gym.ipynb#scrollTo=78BfQoQKOq7z)

In [ ]:
"""!apt-get update > /dev/null 2>&1
!apt-get install cmake > /dev/null 2>&1
!pip install --upgrade setuptools 2>&1
!pip install ez_setup > /dev/null 2>&1
!pip install gym[atari] > /dev/null 2>&1"""

In [ ]:
!pip install gym pyvirtualdisplay > /dev/null 2>&1
!apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1

In [ ]:
## used for downloading videos
import gym
from gym.wrappers import Monitor
import glob
import io
import base64
from IPython.display import HTML
from pyvirtualdisplay import Display
from IPython import display as ipythondisplay

display = Display(visible=0, size=(1400, 900))
display.start()

"""
Utility functions to enable video recording of gym environment 
and displaying it.
To enable video, just do "env = wrap_env(env)""
"""

def show_video():
  mp4list = glob.glob('video/*.mp4')
  if len(mp4list) > 0:
    mp4 = mp4list[0]
    video = io.open(mp4, 'r+b').read()
    encoded = base64.b64encode(video)
    ipythondisplay.display(HTML(data='''<video alt="test" autoplay 
                loop controls style="height: 400px;">
                <source src="data:video/mp4;base64,{0}" type="video/mp4" />
             </video>'''.format(encoded.decode('ascii'))))
  else: 
    print("Could not find video")
    

def wrap_env(env):
  env = Monitor(env, './video', force=True)
  return env




In [ ]:
env = wrap_env(gym.make("LunarLander-v2"))
softmax = nn.Softmax(dim=1)
observation = env.reset()

while True:
  
    env.render()
    
    #your agent goes here
    state_vector = torch.FloatTensor([observation])
    probability= softmax(net(state_vector))

    selected_action = np.random.choice(len(probability.data.numpy()[0]), p=probability.data.numpy()[0])
    new_state, reward, done, info = env.step(selected_action)
   
        
    if done: 
      break;
            
env.close()
show_video()